accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("kakao/login/callback/", views.kakao_callback, name="kakao_callback"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("mypage/", views.mypage, name="mypage"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/block/", views.block, name="block"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    # path("profile/<str:username>/", views.profile, name="profile"),
    path("save/", views.save, name="save"),
    path("notice/", views.notice, name="notice"),
    path("test/", views.test, name="test"),
]

cards/urls.py
from django.urls import path
from . import views

app_name = "cards"

urlpatterns = [
    path("", views.index, name="index"),
    # 개인카드
    path("create/indiv/", views.usercard_create, name="usercard_create"),
    path("create/indiv/2", views.usercard_create2, name="usercard_create2"),
    path("detail/usercard/<int:pk>/", views.usercard_detail, name="usercard_detail"),
    path("<int:pk>/usercard/update/", views.usercard_update, name="usercard_update"),
    path("<int:pk>/usercard/update/2", views.usercard_update2, name="usercard_update2"),
    path("usercard/delete/", views.usercard_delete, name="usercard_delete"),
    path("<int:pk>/usercard/comments/", views.usercard_comment, name="usercard_comment"),
    path(
        "<int:pk>/usercard/comments/2",
        views.usercard_comment2,
        name="usercard_comment2",
    ),
    path("<int:pk>/modal_open/", views.modal_open, name="modal_open"),
    # 그룹카드
    path("create/group/", views.group_create, name="group_create"),
    path("<int:pk>/create/group/2", views.group_create2, name="group_create2"),
    path("detail/group/<int:pk>/", views.group_detail, name="group_detail"),
    path("<int:pk>/group/update/", views.groupcard_update, name="groupcard_update"),
    path("<int:pk>/group/update/2", views.groupcard_update2, name="groupcard_update2"),
    path("<int:pk>/group/delete/", views.groupcard_delete, name="groupcard_delete"),
    path("<int:pk>/gcomments/", views.gcomment_create, name="gcomment_create"),
    path("<int:pk>/gcomments/2", views.gcomment_create2, name="gcomment_create2"),
    path("search/", views.search, name="search"),
    # path(
    #     "<int:cards_pk>/group/<int:comment_pk>/delete/",
    #     views.gcomments_delete,
    #     name="gcomments_delete",
    # ),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

semi_pjt_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from meetings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("cards/", include("cards.urls")),
    path("vocies/", include("vocies.urls")),
    path("accounts/", include("accounts.urls")),
    path("meetings/", include("meetings.urls")),
    path("chat/", include("chat.urls")),
    path("shoppings/", include("shoppings.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")
    blocking = models.ManyToManyField("self", symmetrical=False, related_name="blockers")
    updated_at = models.DateTimeField(auto_now=True)
    profileimage = models.ImageField(upload_to="profile/", blank=True)
    gender = models.CharField(blank=True, max_length=10)
    age_range = models.CharField(blank=True, max_length=10)
    nickname = models.CharField(max_length=40, blank=True)
    introduce = models.CharField(blank=True, max_length=200)
    refresh_token = models.TextField(blank=True)
    tree_notice = models.BooleanField(default=True)
    note_notice = models.BooleanField(default=True)
    notice_tree = models.BooleanField(default=True)
    notice_note = models.BooleanField(default=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = (
            "username",
            "password1",
            "password2",
            "email",
        )
        model = get_user_model()


class UpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "nickname",
            "gender",
            "email",
            "introduce",
            "age_range",
        )
        widgets = {
            "age_range": forms.TimeInput(
                attrs={
                    "class": "form-range",
                    "type": "range",
                    "min": "0",
                    "max": "100",
                    "step": "1",
                    "id": "customRange3",
                    "oninput": "document.getElementById('value2').innerHTML=this.value;",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)

        self.fields["nickname"].widget.attrs = {
            "class": "form-control my-3",
            "placeholder": "닉네임을 입력해주세요.",
        }

        self.fields["gender"].widget.attrs = {
            "class": "form-control my-3",
            "placeholder": "성별을 입력해주세요.",
        }

        self.fields["email"].widget.attrs = {
            "class": "form-control my-3",
            "placeholder": "이메일을 입력해주세요.",
        }

        self.fields["introduce"].widget.attrs = {
            "class": "form-control my-3",
            "placeholder": "자기소개를 입력해주세요.",
        }

accounts/views.py
from multiprocessing import AuthenticationError
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
import requests
from django.contrib import messages
from django.http import JsonResponse
from cards.models import *
from django.db.models import *
import datetime

# Create your views here.
def signup(request):
    gender = request.POST.get("gender")
    age = request.POST.get("age")
    print(gender, age)
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            forms = form.save(commit=False)
            forms.gender = gender
            forms.age = age
            forms.save()
            return redirect("accounts:index")
    else:
        form = SignupForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def index(request):
    return render(request, "accounts/index.html")


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("home")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


import secrets, os

state_token = secrets.token_urlsafe(16)


def kakao_request(request):
    kakao_api = "https://kauth.kakao.com/oauth/authorize?response_type=code"
    redirect_uri = "http://localhost:8000/accounts/kakao/login/callback/"
    client_id = os.getenv("KAKAO_ID")
    return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")


def kakao_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": os.getenv("KAKAO_ID"),
        "redirect_uri": "http://localhost:8000/accounts/kakao/login/callback/",
        "code": request.GET.get("code"),
        "client_secret": os.getenv("KAKAO_SECRET"),
    }
    kakao_token_api = "https://kauth.kakao.com/oauth/token"
    temp = requests.post(kakao_token_api, data=data).json()
    access_token = temp["access_token"]

    headers = {"Authorization": f"bearer ${access_token}"}
    kakao_user_api = "https://kapi.kakao.com/v2/user/me"
    kakao_user_information = requests.get(kakao_user_api, headers=headers).json()
    kakao_id = kakao_user_information["id"]
    kakao_nickname = kakao_user_information["properties"]["nickname"]
    kakao_profile_image = kakao_user_information["properties"]["profile_image"]
    kakao_email = kakao_user_information["kakao_account"].get("email")
    kakao_age_range = kakao_user_information["kakao_account"].get("age_range")
    kakao_gender = kakao_user_information["kakao_account"].get("gender")

    if get_user_model().objects.filter(username=kakao_id).exists():
        kakao_user = get_user_model().objects.get(username=kakao_id)
        kakao_user.refresh_token = temp["refresh_token"]
        kakao_user.profileimage = kakao_profile_image
        kakao_user.save()
    else:
        kakao_login_user = get_user_model().objects.create(
            username=kakao_id,
            nickname=kakao_nickname,
            profileimage=kakao_profile_image,
            email=kakao_email,
            age_range=kakao_age_range,
            gender=kakao_gender,
            refresh_token=temp["refresh_token"],
        )
        kakao_login_user.set_password(str(state_token))
        kakao_login_user.save()
        kakao_user = get_user_model().objects.get(username=kakao_id)
    auth_login(request, kakao_user, backend="django.contrib.auth.backends.ModelBackend")
    if request.user.blockers.count() > 9:
        auth_logout(request)
        messages.error(request, "누적 신고 횟수가 많아 로그인 할 수 없어요.😥")
    else:
        messages.success(request, "오신걸 환영합니다.😀")
    return redirect(request.GET.get("next") or "home")


@login_required
def mypage(request):
    block_users = request.user.blocking.all()
    block_cnt = len(block_users)
    return render(
        request,
        "accounts/mypage.html",
        {
            "user": get_user_model().objects.get(pk=request.user.pk),
            "block_users": block_users,
            "block_cnt": block_cnt,
        },
    )


def logout(request):
    auth_logout(request)
    return redirect("home")


def update(request):
    if request.method == "POST":
        print(request.POST, request.FILES)
        form = UpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:mypage")
    else:
        form = UpdateForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


import requests


def delete(request):
    url = "https://kauth.kakao.com/oauth/token"

    data = {
        "grant_type": "refresh_token",
        "client_id": os.getenv("KAKAO_ID"),
        "refresh_token": request.user.refresh_token,
        "client_secret": os.getenv("KAKAO_SECRET"),
    }

    response = requests.post(url, data=data).json()
    access_token = response["access_token"]
    url = "https://kapi.kakao.com/v1/user/unlink"
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Authorization": f"Bearer ${access_token}",
    }
    response = requests.post(url, headers=headers)
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:index")


@login_required
def follow(request, pk):
    person = get_object_or_404(get_user_model(), pk=pk)
    if person != request.user and request.method == "POST":
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
            is_follow = False
        else:
            person.followers.add(request.user)
            is_follow = True
        context = {
            "isFollow": is_follow,
            "followersCount": person.followers.all().count(),
            "followingsCount": person.followings.all().count(),
        }
        return JsonResponse(context)
    else:
        messages.warning(request, "그건 안됨.")
        return redirect("meetings:index")


@login_required
def block(request, pk):
    person = get_object_or_404(get_user_model(), pk=pk)
    if person != request.user and request.method == "POST":
        if person.blockers.filter(pk=request.user.pk).exists():
            person.blockers.remove(request.user)
            is_follow = False
            messages.success(request, "차단이 해제되었습니다.")
        else:
            person.blockers.add(request.user)
            is_follow = True
            messages.success(request, "차단 되었습니다.")
        context = {
            "isFollow": is_follow,
        }
        return JsonResponse(context)
    else:
        messages.warning(request, "그건 안됨.")
        return redirect("meetings:index")


def profile(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    context = {
        "user": user,
        "followers": user.followers.all(),
        "followings": user.followings.all(),
    }
    return render(request, "accounts/profile.html", context)


@login_required
def save(request):
    if request.method == "POST":
        tree_notice = request.GET.get("p")
        note_notice = request.GET.get("h6")
        if tree_notice == "ON":
            request.user.tree_notice = True
        else:
            request.user.tree_notice = False
        if note_notice == "ON":
            request.user.note_notice = True
        else:
            request.user.note_notice = False
        request.user.save()
        messages.success(request, "저장 성공.😀")
        return JsonResponse({1: 1})
    else:
        messages.error(request, "그렇게는 접근할 수 없어요.😥")
        return redirect("accounts:mypage")


@login_required
def notice(request):
    if request.method == "POST":
        dic = {}
        if request.user.tree_notice:
            if UserCard.objects.filter(user=request.user).exists():
                card = request.user.usercard
                false_comments = card.usercomment_set.filter(read=False)
                for i in false_comments:
                    if i.created_at not in dic:
                        dic[i.created_at.strftime("%Y-%m-%dT%H:%M:%S")] = (
                            i.content,
                            i.user.nickname,
                            "card",
                            card.pk,
                        )
                    else:
                        dic[
                            (i.created_at + datetime.timedelta(minutes=1)).strftime(
                                "%Y-%m-%dT%H:%M:%S"
                            )
                        ] = (
                            i.content,
                            i.user.nickname,
                            "card",
                            card.pk,
                        )
        if request.user.note_notice:
            if request.user.user_to.filter(read=False).exists():
                false_notes = request.user.user_to.filter(read=False)
                for i in false_notes:
                    if i.created_at not in dic:
                        dic[i.created_at.strftime("%Y-%m-%dT%H:%M:%S")] = (
                            i.title,
                            i.from_user.nickname,
                            "note",
                            i.pk,
                        )
                    else:
                        dic[
                            (i.created_at + datetime.timedelta(minutes=1)).strftime(

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %} 

<h1>임시 페이지</h1>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}

{% comment %} 기존 로그인폼(예비용) {% endcomment %}

 <div class='d-flex justify-content-center'>
  <div style='width:30rem' class='my-5'>
    <h1 class='text-center my-5'>로그인 페이지</h1>
      <form action="{% url 'accounts:login' %}" method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-grid">
          <input type="submit" value="로그인" class="btn btn-primary">

        </div>
    </form>
  </div>
</div> 

<div class='d-flex justify-content-center'>
  <div style='width:30rem' class='my-5'>
    <h1 class='text-center my-5'>로그인</h1>
        <div class="d-grid">
          <a href="{% url 'accounts:kakao' %}">
            <img src="{% static 'images/kakao_login.jpg' %}" alt="카카오 간편로그인" style='width:30rem' class='rounded-4'>
          </a>
        </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:400,500,600,700&amp;display=swap">
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
  <style>
    body {
      background-image: url("{% static 'images/그룹카드배경1.jpg' %}");
      background-repeat: repeat;
      background-size: cover;

      {
        % comment %
      }

      color: white;

      {
        % endcomment %
      }
    }

    :root {
      --surface-color: #fff;
      --curve: 40;
    }

    * {
      box-sizing: border-box;
    }

    .cards {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 2rem;
      margin: 4rem 5vw;
      padding: 0;
      list-style-type: none;
    }

    .card2 {
      position: relative;
      display: block;
      width: 20rem;
      height: auto;
      border-radius: calc(var(--curve) * 1px);
      overflow: hidden;
      text-decoration: none;
    }

    .card__image {
      width: 100%;
      height: 20rem;
    }

    .card__overlay {
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      z-index: 1;
      border-radius: calc(var(--curve) * 1px);
      background-color: var(--surface-color);
      transform: translateY(100%);
      transition: 0.2s ease-in-out;
    }

    .card2:hover .card__overlay {
      transform: translateY(0);
    }

    .card__header {
      position: relative;
      display: flex;
      align-items: center;
      gap: 2em;
      padding: 0.7em;
      border-radius: calc(var(--curve) * 1px) 0 0 0;
      background-color: var(--surface-color);
      transform: translateY(-100%);
      transition: 0.2s ease-in-out;
    }

    .card__arc {
      width: 80px;
      height: 80px;
      position: absolute;
      bottom: 100%;
      right: 0;
      z-index: 1;
    }

    .card__arc path {
      fill: var(--surface-color);
      d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }

    .card2:hover .card__header {
      transform: translateY(0);
    }

    .card__thumb {
      flex-shrink: 0;
      width: 50px;
      height: 50px;
      border-radius: 50%;
    }

    .card__title {
      font-size: 1em;
      margin: 0 0 0.3em;
      color: #6A515E;
    }

    .card__tagline {
      display: block;
      margin: 1em 0;
      font-family: "MockFlowFont";
      font-size: 0.8em;
      color: #6A515E;
    }

    .card__status {
      font-size: 0.8em;
      color: #6A515E;
    }

    .card__description {
      padding: 0 2em 2em;
      margin: 0;
      color: #6A515E;
      font-family: "MockFlowFont";
      display: -webkit-box;
      -webkit-box-orient: vertical;
      -webkit-line-clamp: 3;
      overflow: hidden;
    }

    #profileimage {
      box-shadow: 0 8px 5px rgba(0, 0, 0, 0.5);
    }
  </style>
  <div class="row row-cols-6 justify-content-evenly" style='width:100%'>
    <!-- 벽난로 주인 프로필 -->
    <div class='col col-lg-5 ms-2 my-5'>
      <p class=' my-5 fs-1 text-center'>개인 프로필</p>
      <div class='row'>
        <div class='col-5 d-flex flex-column align-content-center align-items-center'>
          <div class='text-center'>
            {% if user.profileimage %}
              <img id="profileimage" src="{{ user.profileimage }}" class="rounded-pill" style='width:10rem;'>
            {% else %}
              <img src="{% static 'images/게스트.png' %}" class="rounded-2" style='width:10rem;'>
            {% endif %}
          </div>
          <div class='text-center my-4'>
            {% if request.user == user %}
              <a href="{% url 'accounts:mypage' %}" class='btn btn-outline-primary'>마이페이지</a>
            {% else %}
            </div>
            {% csrf_token %}
            {% if request.user not in user.followers.all %}
              <button class="favorite-button" data-user-id="{{user.pk}}" value="{{user.pk}}" onclick="follow(event)">
                <div class="icon">
                  <div class="star"></div>
                </div>
                <span id="span">Follow</span>
              </button>
            {% else %}
              <button class="favorite-button active" data-user-id="{{user.pk}}" value="{{user.pk}}" onclick="follow(event)">
                <div class="icon">
                  <div class="star"></div>
                </div>
                <span id="span">UnFollow</span>
              </button>
            {% endif %}

            <div id="follow-cnt">

            {% endif %}
          </div>
        </div>
        <div class='col-7 '>
          <div>
            <p>
              이름 :
              {{ user.nickname }}
            </p>
            <p>
              성별 :
              {{ user.gender }}
            </p>
            <p>
              나이 :
              {{ user.age_range }}</p>
            <div class='d-flex'>
              <h5 class="me-1 text-primary"><a type="button" data-bs-toggle="modal" data-bs-target="#follower">팔로워</a> :
              </h5>
              <h5 class='me-3' id='followers-cnt'>
                {{ user.followers.count }}</h5>
                <h5 class="me-1 text-primary"><a type="button" data-bs-toggle="modal" data-bs-target="#following">팔로잉</a> :
                </h5>
              <h5 class='me-3' id='followings-cnt'>
                {{ user.followings.count }}</h5>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- 벽난로 -->
    <div class='col-12 col-lg-3 ms-2 my-5'>
      <div class='mb-5 d-flex justify-content-center'>
        <div>
          <h1 class='my-5 text-center'>
            개인 벽난로
          </h1>
          {% if user.usercard %}
            <a href="{% url 'cards:usercard_detail' user.usercard.pk %}" class="card2">
              <div style='position:relative'>

                {% if user.usercard.chimneys == 9 %}
                  <img src="/static/images/벽난로{{ user.usercard.chimneys }}.png" class="card__image" alt=""/>
                {% else %}
                  <img src="/static/images/벽난로{{ user.usercard.chimneys }}.jpg" class="card__image" alt=""/>
                {% endif %}
                <div style='position: absolute; top:1rem; left:7.8rem;z-index: 20'>
                  <img src='/static/images/유저장식{{ user.usercard.userdeco }}.png' style='width:5rem; height:5rem;'>
                </div>
              </div>

              <div class="card__overlay">
                <div class="card__header">
                  <svg class="card__arc" xmlns="http://www.w3.org/2000/svg">
                    <path/></svg>
                  {% if user.profileimage %}
                    <img class="card__thumb" src="{{ user.profileimage }}"/>
                  {% else %}
                    <img class="card__thumb" src="{% static 'images/게스트.png' %}"/>

                  {% endif %}
                  <div class="card__header-text">
                    <h3 class="card__title">{{ user.nickname }}</h3>
                    <span class="card__status">{{ user.usercard.title }}</span>
                  </div>
                </div>
                <p class="card__description">{{ user.usercard.content }}</p>
              </div>
            </a>
          {% else %}
            {%if request.user == user %}
            <div class="p-5 my-5">
              <a href="{% url 'cards:usercard_create' %}" class="btn" style='background-color:orangered;color:white'>
                개인 벽난로를 생성해주세요!
              </a>
            </div>
            {% else %}
            <p>아직 개인 벽난로가 없어요.😂</p>
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="follower" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body pt-1">
          {% for follower in user.followers.all %}
          <div class='d-flex justify-content-center'>
            <a href="{% url 'accounts:profile' follower.pk %}">{{follower.nickname}}</a>
          </div>
          {% endfor %}
          <div class='d-grid mt-5'>
            <button type="button" class="btn btn-success" data-bs-dismiss="modal" aria-label="Close">닫기</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="following" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body pt-1">
          {% for following in user.followings.all %}
          <div class='d-flex justify-content-center'>
            <a href="{% url 'accounts:profile' following.pk %}">{{following.nickname}}</a>
          </div>
          {% endfor %}
          <div class='d-grid mt-5'>
            <button type="button" class="btn btn-success" data-bs-dismiss="modal" aria-label="Close">닫기</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.4.0/gsap.min.js"></script>
  <script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
  <script>
    new Snowflakes();
  </script>
  <!-- follow -->
  <script>
    function follow(e) {
      const button = e.target
      if (button.classList.contains('animated')) {
        return
      }
      button
        .classList
        .add('animated')

      gsap.to(button, {
        keyframes: [
          {
            '--star-y': '-36px',
            duration: .3,
            ease: 'power2.out'
          }, {
            '--star-y': '48px',
            '--star-scale': .4,
            duration: .325,
            onStart() {
              button
                .classList
                .add('star-round')
            }
          }, {
            '--star-y': '-64px',
            '--star-scale': 1,
            duration: .45,
            ease: 'power2.out',
            onStart() {
              button
                .classList
                .toggle('active')
              setTimeout(() => button.classList.remove('star-round'), 100)
            }
          }, {
            '--star-y': '0px',
            duration: .45,
            ease: 'power2.in'
          }, {
            '--button-y': '3px',
            duration: .11
          }, {
            '--button-y': '0px',
            '--star-face-scale': .65,
            duration: .125
          }, {
            '--star-face-scale': 1,
            duration: .15
          }
        ],
        clearProps: true,
        onComplete() {
          button
            .classList
            .remove('animated')
        }
      })

      gsap.to(button, {
        keyframes: [
          {
            '--star-hole-scale': .8,
            duration: .5,
            ease: 'elastic.out(1, .75)'
          }, {
            '--star-hole-scale': 0,
            duration: .2,
            delay: .2
          }
        ]
      })

      gsap.to(button, {
        '--star-rotate': '360deg',
        duration: 1.55,
        clearProps: true
      })
      const csrftoken = document
        .querySelector('[name=csrfmiddlewaretoken]')
        .value
        axios({
          method: 'post',
          url: `/accounts/${e.target.dataset.userId}/follow/`,
          headers: {
            'X-CSRFToken': csrftoken
          },
          data: {
            'note_pk': event.target.dataset.userId
          }
        })
        .then(response => {
          console.log(response.data.followersCount)
          console.log(response.data.followingsCount)
          if (response.data.isFollow === true) {
            const span = document.querySelector('#span')
            span.innerText = 'UnFollow'
          } else {
            const span = document.querySelector('#span')
            span.innerText = 'Follow'
          }
          const followingsCnt = document.querySelector('#followings-cnt')
          const followersCnt = document.querySelector('#followers-cnt')
          followingsCnt.innerText = `${response.data.followingsCount}`
          followersCnt.innerText = `${response.data.followersCount}`
        })
    }
  </script>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class='d-flex justify-content-center'>
    <div style='width:30rem;'>
        <h1 class='text-center my-4'>회원가입</h1>
        <form action="{% url 'accounts:signup' %}" method='POST' enctype='multipart/form-data'>
            {% csrf_token %}
            <select class="form-select form-select-lg mb-3" name='gender'>
                <option value="1">남자</option>
                <option value="0">여자</option>
            </select>
            <input type="date" name='age'>
            {% bootstrap_form form %}
            <div class='d-grid'>
                <input type="submit" value="회원가입" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock  %}