accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("kakao/login/callback/", views.kakao_callback, name="kakao_callback"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("mypage/", views.mypage, name="mypage"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/block/", views.block, name="block"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    # path("profile/<str:username>/", views.profile, name="profile"),
    path("save/", views.save, name="save"),
    path("notice/", views.notice, name="notice"),
    path("test/", views.test, name="test"),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

notes/urls.py
from . import views
from django.urls import path

app_name = "notes"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

semi_pjt_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from meetings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("cards/", include("cards.urls")),
    path("vocies/", include("vocies.urls")),
    path("accounts/", include("accounts.urls")),
    path("meetings/", include("meetings.urls")),
    path("chat/", include("chat.urls")),
    path("shoppings/", include("shoppings.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Notes(models.Model):
    from_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_from"
    )
    to_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_to"
    )
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    important = models.BooleanField(default=False)
    garbage = models.BooleanField(default=False)

notes/forms.py
from .models import *
from django import forms


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ("title", "content")
        labels = {
            "title": "제목",
            "content": "내용",
        }

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *
from django.http import JsonResponse


@login_required
def index(request):
    notes = request.user.user_to.order_by("-created_at")
    to_notes = request.user.user_from.order_by("-created_at")

    return render(
        request,
        "notes/index.html",
        {"notes": notes, "to_notes": to_notes},
    )


@login_required
def send(request, pk):
    to_user = get_object_or_404(get_user_model(), pk=pk)
    form = NotesForm(request.POST or None)
    if form.is_valid():
        temp = form.save(commit=False)
        temp.from_user = request.user
        temp.to_user = to_user
        temp.save()
        if to_user.note_notice:
            to_user.notice_note = False
            to_user.save()
        messages.success(request, "쪽지 전송 완료.😀")
        return redirect("meetings:index")
    context = {
        "form": form,
        "to_user": to_user,
    }
    return render(request, "notes/send.html", context)


def detail(request, pk):
    note = get_object_or_404(Notes, pk=pk)

    if request.user == note.to_user:
        if not note.read:
            note.read = True
            note.save()
        if not request.user.user_to.filter(read=False).exists():
            request.user.notice_note = True
            request.user.save()
        return render(request, "notes/detail.html", {"note": note})
    elif request.user == note.from_user:
        return render(request, "notes/detail.html", {"note": note})
    else:
        messages.error(request, "그렇게는 볼 수 없어요.😅")
        return redirect("notes:index")


def delete(request, pk):
    note = get_object_or_404(Notes, pk=pk)
    print(request.POST)
    if request.user == note.to_user and request.method == "POST":
        note.delete()
        return JsonResponse({"pk": pk})
    else:
        messages.error(request, "남의 쪽지는 지울 수 없어요.😅")
        return redirect("notes:index")

notes/templates/notes/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}

<style>
    
    body {
      background-image : url('{% static 'images/쪽지배경.png' %}');
      background-repeat : repeat;
      background-size : cover;
      {% comment %} color:white; {% endcomment %}
    }

    #modal.modal-overlay {
        width: 100%;
        height: 100%;
        position: absolute;
        left: 0;
        top: 0;
        display: none;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        background: rgba(255, 255, 255, 0.25);
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
        backdrop-filter: blur(1.5px);
        -webkit-backdrop-filter: blur(1.5px);
        border-radius: 10px;
        border: 1px solid rgba(255, 255, 255, 0.18);
        z-index: 100;
    }
    #modal .modal-window {
        background: rgba(21, 22, 22, 0.7);
        box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );
        backdrop-filter: blur( 13.5px );
        -webkit-backdrop-filter: blur( 13.5px );
        border-radius: 10px;
        border: 1px solid rgba( 255, 255, 255, 0.18 );
        width: 200px;
        height: 250px;
        position: relative;
        top: -100px;
        padding: 10px;
    }
    #modal .title {
        padding-left: 10px;
        display: inline;
        text-shadow: 1px 1px 2px gray;
        color: white;
        
    }
    #modal .title h2 {
        display: inline;
    }
    #modal .close-area {
        display: inline;
        float: right;
        padding-right: 10px;
        cursor: pointer;
        text-shadow: 1px 1px 2px gray;
        color: white;
    }
    
    #modal .content {
        margin-top: 20px;
        padding: 0px 10px;
        text-shadow: 1px 1px 2px gray;
        color: white;
    }

    #container {
      position: relative;
      margin-top: 100px;
    }

    #profileimage {
      -webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
      -moz-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
      -ms-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
      -o-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
      box-shadow: 0 5px 7px rgba(0,0,0,0.5);
      position: absolute;
      top: 10%;
      z-index: 1;
    }

    #cust-card {
      box-shadow: 0 10px 5px rgba(0,0,0,0.5);
    }
    p {
      white-space: pre-line;
    }
    hr {
      height: 2px;
    }

</style>
<script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
<script>
  new Snowflakes();
</script>

</head>
<body>


<div id="container" class="container mt-4" style="max-width:550px;">
  <div class="d-flex justify-content-center mb-2" id="profile">
    <img id="profileimage" src="{{note.from_user.profileimage}}" alt="프로필 이미지" style="width: 120px; height:120px;" class="rounded-circle">
  </div>
    <div id="container" class="container p-0">
      <div class="card" style="border-radius: 18px;"  id="cust-card">
        <div style="height: 70px;">
        </div>
        <hr>
        <div class="container ms-3">
          <div class="fs-4 fw-bold">{{ note.title }}</div>
          <div class="fs-5">
            <p>{{ note.content }}</p>
          </div>
        </div>
        <hr>
          <a style="text-decoration:none;" href="{% url 'notes:send' note.from_user.pk %}" class="fs-6 d-flex justify-content-end me-3 text-black custom-link">답장하기</a>
        <div class="d-flex justify-content-end mx-3">          
          <a class="custom-link fs-4" id="btn-modal">
            <span class="fs-6">from. </span>
            {% if note.from_user.nickname %}
            {{ note.from_user.nickname }}
            {% else %}
            {{ note.from_user.username }}
            {% endif %}
          </a>
        </div>
        
        <div class="d-flex justify-content-end">
          <small class="mx-3 mb-2">
            {{ note.created_at|date:'o.m.d' }} {{ note.created_at|time:"H:i" }}
          </small>
        </div>
        <div id="modal" class="modal-overlay">
            <div class="modal-window">
                <div class="title">
                    <h2>
                      {% if note.from_user.nickname %}
                      {{ note.from_user.nickname }}
                      {% else %}
                      {{ note.from_user.username }}
                      {% endif %}
                    </h2>
                </div>
                <div class="close-area">X</div>
                <div class="content">
                    <h3><a href="{% url 'accounts:profile' request.user.pk %}" class="text-decoration-none text-white">프로필</a></h3>
                    <h3><a href="{% url 'notes:send' note.from_user.pk %}" class="text-decoration-none text-white">쪽지</a></h3>
                    <h3><a href="{% url 'accounts:follow' request.user.pk %}" class="text-decoration-none text-white">팔로우</a></h3>
                    <h3><a href="{% url 'accounts:block' request.user.pk %}" class="text-decoration-none text-white">차단</a></h3>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>
<script>
const loremIpsum = document.getElementById("lorem-ipsum")
fetch("https://baconipsum.com/api/?type=all-meat&paras=200&format=html")
    .then(response => response.text())
    .then(result => loremIpsum.innerHTML = result)
const modal = document.getElementById("modal")
function modalOn() {
    modal.style.display = "flex"
}
function isModalOn() {
    return modal.style.display === "flex"
}
function modalOff() {
    modal.style.display = "none"
}
const btnModal = document.getElementById("btn-modal")
btnModal.addEventListener("click", e => {
    modalOn()
})
const closeBtn = modal.querySelector(".close-area")
closeBtn.addEventListener("click", e => {
    modalOff()
})
modal.addEventListener("click", e => {
    const evTarget = e.target
    if(evTarget.classList.contains("modal-overlay")) {
        modalOff()
    }
})
window.addEventListener("keyup", e => {
    if(isModalOn() && e.key === "Escape") {
        modalOff()
    }
})
</script>
{% endblock %}

notes/templates/notes/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}


<img src="" alt="">
<div class="container fs-5 mt-4">
  <div id="main_in" class="d-flex justify-content-center">
    <table class="list-table">
      <thead>
        <th class="fs-2 fw-bold">받은 편지함</th>
        <tr>
          <th width="150" class="tl">보낸사람</th>
          <th width="400" class="tl">제목</th>
          <th width="200" class="tc">날짜</th>
          <th width="100" class="tc">읽음</th>
          <th width="100" class="tc">삭제</th>
        </tr>
      </thead>
          <tbody>
          {% for note in notes %}
          {% if note.read == 1 %}
              <tr class="text-muted" id="{{note.pk}}">
                <td>
                  {% if note.from_user.nickname %}
                  {{ note.from_user.nickname }}
                  {% else %}
                  {{ note.from_user.username }}
                  {% endif %}
                </td> <!---보낸이 -->
                <td><a class="text-muted" style="text-decoration:none;" href="{% url 'notes:detail' note.pk %}">{{ note.title }}</a></td> <!---제목 -->
                <td class="tc">{{ note.created_at|date:'o.m.d' }} {{ note.created_at|time:"H:i" }}</td> <!---보낸시간 -->
                {% if note.read == 1 %}
                <td>읽음</td> <!---읽음 -->
                {% else %}
                <td>안읽음</td> <!---읽음 -->
                {% endif %}
                <td class="tc">
                  {% csrf_token %}
                  <button id="custom-btn" style="background-color:transparent;">
                    <i xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16" data-note-id="{{note.pk}}" value="{{note.pk}}" onclick="remove(event)"></i>
                  </button>
                </td> <!---삭제 -->
              </tr>
            {% else %}
            <tr id="{{note.pk}}">
              <td>
                {% if note.from_user.nickname %}
                {{note.from_user.nickname}}
                {% else %}
                {{note.from_user.username}}
                {% endif %}
              </td> <!---보낸이 -->
              <td><a class="custom-link" style="text-decoration:none; color:black;" href="{% url 'notes:detail' note.pk %}">{{ note.title }}</a></td> <!---제목 -->
              <td class="tc">{{ note.created_at|date:'o.m.d' }} {{ note.created_at|time:"H:i" }}</td> <!---보낸시간 -->
              {% if note.read == 1 %}
              <td>읽음</td> <!---읽음 -->
              {% else %}
              <td>안읽음</td> <!---읽음 -->
              {% endif %}
              <td class="tc">
                  {% csrf_token %}
                  <button id="custom-btn" style="background-color:transparent;">
                    <i xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16" data-note-id="{{note.pk}}" value="{{note.pk}}" onclick="remove(event)"></i>
                  </button>
              </td> <!---삭제 -->
            </tr>
            {% endif %}
          {% endfor %}
          </tbody>
    </table>
  </div>
</div>

<hr/>
<div class="container fs-5 mt-4">
  
  <div id="main_in" class="d-flex justify-content-center">
    <table class="list-table">
      <thead>
        <th class="fs-2 fw-bold">보낸 편지함</th>
        <th><span class="fs-6 text-muted p-2">상대방이 읽으면 읽음처리 됩니다.</span></th>
        <tr>
          <th width="150" class="tl">받는사람</th>
          <th width="400" class="tl">제목</th>
          <th width="200" class="tc">날짜</th>
          <th width="100" class="tc">읽음</th>
          <th width="100" class="tc"></th>
        </tr>
      </thead>
          <tbody>
          {% for note in to_notes %}
          <div id="{{note.pk}}">
            {% if note.read == 1 %}
              <tr class="text-muted">
                <td>
                  {% if note.to_user.nickname %}
                  {{note.to_user.nickname}}
                  {% else %}
                  {{note.to_user.username}}
                  {% endif %}
                </td> <!---보낸이 -->
                <td><a class="text-muted" style="text-decoration:none;" href="{% url 'notes:detail' note.pk %}">{{ note.title }}</a></td> <!---제목 -->
                <td class="tc">{{ note.created_at|date:'o.m.d' }} {{ note.created_at|time:"H:i" }}</td> <!---보낸시간 -->
                {% if note.read == 1 %}
                <td>읽음</td> <!---읽음 -->
                {% else %}
                <td>안읽음</td> <!---읽음 -->
                {% endif %}
                <td class="tc">
                </td> <!---삭제 -->
              </tr>
            {% else %}
            <tr>
              <td>
                {% if note.to_user.nickname %}
                {{note.to_user.nickname}}
                {% else %}
                {{note.to_user.username}}
                {% endif %}
              </td> <!---내가 보낸 -->
              <td><a class="custom-link" style="text-decoration:none; color:black;" href="{% url 'notes:detail' note.pk %}">{{ note.title }}</a></td> <!---제목 -->
              <td class="tc">{{ note.created_at|date:'o.m.d' }} {{ note.created_at|time:"H:i" }}</td> <!---보낸시간 -->
              {% if note.read == 1 %}
              <td>읽음</td> <!---읽음 -->
              {% else %}
              <td>안읽음</td> <!---읽음 -->
              {% endif %}
              <td class="tc">
              </td> <!---삭제 -->
            </tr>
            {% endif %}
          </div>
          {% endfor %}
          </tbody>
    </table>
  </div>
</div>
<path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  function remove(event) {
  console.log(event.target.dataset.noteId)
  var delete_warning = confirm('쪽지를 삭제하시겠습니까?')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  if (delete_warning == true) {
    axios({
      method: 'post',
      url: `/notes/${event.target.dataset.noteId}/delete/`,
      headers: {'X-CSRFToken': csrftoken},
      data: {'note_pk': event.target.dataset.noteId},
    })
    .then(response => {
      const resdata = response.data.pk
      const div = document.getElementById(resdata)
      console.log(div)
      div.remove()
    })
  }
}
</script>


<style>
  body {
    background-image : url('{% static 'images/그룹카드배경3.jpg' %}');
    background-repeat : repeat;
    background-size : cover;
    {% comment %} color:white; {% endcomment %}
   }
   
  #main_head {
    width: 100%;
    background:#003f51;	
  }
  #main_head_in {
    width: 1200px;
    height: 50px;
  }
  #main_t {
    position: absolute;
    top:5px; 
  }
  #mem_log {
    font-size: 14px;
    color:white;
    padding-top:10px;
    text-align: right;
  }
  #mem_log a{
    color:white;
  }
  #mlog {
    margin-left: 40px; 
  }
</style>

{% endblock %}

notes/templates/notes/send.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}

<script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
<script>
  new Snowflakes();
</script>

<style>
  body {
    background-image : url('{% static 'images/쪽지배경.png' %}');
    background-repeat : repeat;
    background-size : cover;
    {% comment %} color:white; {% endcomment %}
  }

  #profileimage {
    -webkit-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    -moz-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    -ms-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    -o-box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    box-shadow: 1px 1px 10px 7px white;
  }
</style>

<div class="container my-5" style="max-width:500px;">
  <div class="d-flex justify-content-center mb-2" id="profile">
    <img id="profileimage" src="{{to_user.profileimage}}" alt="프로필 이미지" style="width: 25%; height:25%;" class="rounded-circle">
  </div>
  <fieldset disabled>
    <div class="mb-3">
      <label for="disabledTextInput" class="form-label text-white">받는 사람</label>
      {% if to_user.nickname %}
      <input type="text" id="disabledTextInput" class="form-control" placeholder="{{to_user.nickname}}">
      {% else %}
      <input type="text" id="disabledTextInput" class="form-control" placeholder="{{to_user.username}}">
      {% endif %}
    </div>
  </fieldset>
  <form action="" method="POST" class="text-white">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="text-end">
      {% bootstrap_button button_type='submit' content='전송' %}
    </div>
  </form>
</div>
{% endblock %}