chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

semi_pjt_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from meetings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("cards/", include("cards.urls")),
    path("vocies/", include("vocies.urls")),
    path("accounts/", include("accounts.urls")),
    path("meetings/", include("meetings.urls")),
    path("chat/", include("chat.urls")),
    path("shoppings/", include("shoppings.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vocies/urls.py
from django.urls import path
from . import views

app_name = "vocies"

urlpatterns = [
    path("", views.index, name="index"),
    path("myvocie/", views.myvocie, name="myvocie"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/comment/", views.comment, name="comment"),
    path("manage_page/", views.manage_page, name="manage_page"),
    path("<int:pk>/<int:super_pk>/delete_comment/", views.delete_comment, name="delete_comment"),
]

vocies/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Vocie(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="vocie/", blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="vocies"
    )


class Comment(models.Model):
    content = models.TextField()
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vocie = models.ForeignKey(Vocie, on_delete=models.CASCADE, related_name="vocie_comment")
    created_at = models.DateTimeField(auto_now_add=True)

vocies/forms.py
from .models import *
from django import forms


class VocieForm(forms.ModelForm):
    class Meta:
        model = Vocie
        fields = (
            "title",
            "content",
            "image",
        )
        labels = {
            "title": "문의 제목",
            "content": "문의 내용",
            "image": "참조 이미지(선택)",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {
            "content",
        }
        labels = {
            "content": "답변 내용",
        }

vocies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from .forms import *
from .models import *
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request, "vocies/index.html")


@login_required
def myvocie(request):
    return render(request, "vocies/myvocie.html", {"vocies": request.user.vocies.all()})


@login_required
def create(request):
    form = VocieForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        temp = form.save(commit=False)
        temp.user = request.user
        temp.save()
        return redirect("vocies:index")
    return render(request, "vocies/create.html", {"form": form})


@login_required
def detail(request, pk):
    vocie = get_object_or_404(Vocie, pk=pk)
    if request.user == vocie.user or request.user.is_superuser:
        context = {
            "vocie": vocie,
            "form": CommentForm(),
            "comments": vocie.vocie_comment.all(),
        }
        return render(request, "vocies/detail.html", context)
    messages.warning(request, "작성자만 접근할 수 있습니다.")
    return redirect("vocies:index")

@login_required
def update(request, pk):
    vocie = get_object_or_404(Vocie, pk=pk)
    if request.user == vocie.user:
        if request.method == 'POST':
            form = VocieForm(request.POST, request.FILES, instance=vocie)
            if form.is_valid():
                form.save()
                return redirect("vocies:detail", vocie.pk)
        else:
            form = VocieForm(instance=vocie)
        return render(request, "vocies/update.html", {"form": form})
    else:
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("vocies:detail", pk)


@login_required
def comment(request, pk):
    if request.user.is_superuser:
        form = CommentForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.vocie = Vocie.objects.get(pk=pk)
            temp.manager = request.user
            temp.save()
            return redirect("vocies:detail", pk)
    messages.warning(request, "관리자만 접근할 수 있습니다.")
    return redirect("vocies:index")


def delete_comment(request, pk, super_pk):
    if request.user.is_superuser:
        comment_delete = Comment.objects.get(pk=pk)
        comment_delete.delete()
    return redirect("vocies:detail", super_pk)


@permission_required('vocies.index', raise_exception=True)
def manage_page(request):
    return render(request, "vocies/manage_page.html", {"vocies": Vocie.objects.order_by("-pk")})

vocies/templates/vocies/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
  <div class="content">

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10">

          <div class="row justify-content-center">
            <div class="col-md-6">

              <h3 class="heading mb-4">문의 작성하기</h3>
              <p></p>

              <p><img src="{%static "images/as.svg"%}" alt="Image" class="img-fluid"></p>

            </div>
            <div class="col-md-6">
              <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type='submit' content='문의 작성' button_class='btn btn-primary' %}
              </form>
              <div id="form-message-warning mt-4"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    body {
      font-family: "Roboto", sans-serif;
      background-color: #fff;
      line-height: 1.9;
      color: #8c8c8c;
    }

    .h1,
    .h2,
    .h3,
    .h4,
    .h5,
    .h6,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Roboto", sans-serif;
      color: #000;
    }

    a {
      -webkit-transition: 0.3s all ease;
      -o-transition: 0.3s all ease;
      transition: 0.3s all ease;
    }

    a,
    a:hover {
      text-decoration: none !important;
    }

    .text-black {
      color: #000;
    }

    .content {
      padding: 7rem 0;
    }

    .heading {
      font-size: 2.5rem;
      font-weight: 900;
    }

    .form-control {
      border: none;
      background: #f3f3f3;
    }

    .form-control:active,
    .form-control:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
      background: #f3f3f3;
    }

    .col-form-label {
      color: #000;
    }

    .btn,
    .custom-select,
    .form-control {
      height: 50px;
    }

    .custom-select:active,
    .custom-select:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
    }

    .btn {
      border: none;
      border-radius: 4px !important;
    }

    .btn.btn-primary {
      background: #000;
      color: #fff;
      padding: 15px 20px;
    }

    .btn:hover {
      color: #fff;
    }

    .btn:active,
    .btn:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
    }

    .box {
      padding: 40px;
      background: #fff;
      -webkit-box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
      box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
    }

    .box h3 {
      font-size: 14px;
      margin-bottom: 30px;
      text-align: center;
    }

    label.error {
      font-size: 12px;
      color: red;
    }

    #message {
      resize: vertical;
    }

    #form-message-success,
    #form-message-warning {
      display: none;
    }

    #form-message-warning {
      color: #B90B0B;
    }

    #form-message-success {
      color: #55A44E;
      font-size: 18px;
      font-weight: bold;
    }

    .submitting {
      float: left;
      width: 100%;
      padding: 10px 0;
      display: none;
      font-weight: bold;
      font-size: 12px;
      color: #000;
    }
  </style>
{% endblock content %}

vocies/templates/vocies/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
  <div class="content">

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10">

          <div class="row justify-content-center">
            <div class="col-md-6">

              <p><img src="{%static "images/as.svg"%}" alt="Image" class="img-fluid"></p>

            </div>
            <div class="col-md-6">
              <h1>{{ vocie.title }}</h1>
              <p>{{ vocie.created_at }}
                |
                <span>{{ vocie.user.nickname }}</span></p>
              {% if vocie.image %}
                <img src="{{ vocie.image.url }}" alt="{{ vocie.image }}">
              {% endif %}
              <p style="white-space: pre-line;">{{ vocie.content }}</p>
              <a href="{% url 'vocies:update' vocie.pk %}" class="btn btn-outline-success">수정하기</a>
              <!-- 답변 -->
              <!-- 어드민만 답변달 수 있게 -->
              {% if user.is_superuser %}
                <form action="{% url 'vocies:comment' vocie.pk %}" method="POST">
                  {% csrf_token %}
                  {% bootstrap_form form %}
                  {% bootstrap_button button_type="submit" content="OK" button_class="btn btn-primary" %}
                </form>
              {% endif %}
              <div id="form-message-warning mt-4"></div>
              <div class="my-4">
                <h4 class="my-3">문의 답변</h3>

                {% for comment in comments %}
                  <div>
                    <p style="white-space: pre-line;">{{ comment.content }}</p>
                    {% if user.is_superuser %}
                      <a href="{% url 'vocies:delete_comment' comment.pk vocie.pk %}" class="btn btn-outline-danger">삭제</a>
                    {% endif %}
                  </div>
                  {% empty %}
                  <p>아직 답변이 없습니다.</p>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    body {
      font-family: "Roboto", sans-serif;
      background-color: #fff;
      line-height: 1.9;
      color: #8c8c8c;
    }

    .h1,
    .h2,
    .h3,
    .h4,
    .h5,
    .h6,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Roboto", sans-serif;
      color: #000;
    }

    a {
      -webkit-transition: 0.3s all ease;
      -o-transition: 0.3s all ease;
      transition: 0.3s all ease;
    }

    a,
    a:hover {
      text-decoration: none !important;
    }

    .text-black {
      color: #000;
    }

    .content {
      padding: 7rem 0;
    }

    .heading {
      font-size: 2.5rem;
      font-weight: 900;
    }

    .form-control {
      border: none;
      background: #f3f3f3;
    }

    .form-control:active,
    .form-control:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
      background: #f3f3f3;
    }

    .col-form-label {
      color: #000;
    }

    .btn,
    .custom-select,
    .form-control {
      height: 50px;
    }

    .custom-select:active,
    .custom-select:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
    }

    .btn {
      border: none;
      border-radius: 4px !important;
    }

    .btn.btn-primary {
      background: #000;
      color: #fff;
      padding: 15px 20px;
    }

    .btn:hover {
      color: #fff;
    }

    .btn:active,
    .btn:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
    }

    .box {
      padding: 40px;
      background: #fff;
      -webkit-box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
      box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
    }

    .box h3 {
      font-size: 14px;
      margin-bottom: 30px;
      text-align: center;
    }

    label.error {
      font-size: 12px;
      color: red;
    }

    #message {
      resize: vertical;
    }

    #form-message-success,
    #form-message-warning {
      display: none;
    }

    #form-message-warning {
      color: #B90B0B;
    }

    #form-message-success {
      color: #55A44E;
      font-size: 18px;
      font-weight: bold;
    }

    .submitting {
      float: left;
      width: 100%;
      padding: 10px 0;
      display: none;
      font-weight: bold;
      font-size: 12px;
      color: #000;
    }
  </style>
{% endblock content %}

vocies/templates/vocies/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
  <main class="container">
    <div>
      <article class="cont_public" id="mArticle">
        <div class="d-flex justify-content-between">
          <h3 class="tit_public my-4">
            문의
          </h3>
          {% if user.is_superuser %}
            <a href="{% url 'vocies:manage_page' %}" class="tit_public my-4 text-decoration-none text-muted">문의답변</a>
          {% else %}
            <a href="{% url 'vocies:myvocie' %}" class="tit_public my-4 text-decoration-none text-muted">내 문의보기</a>
          {% endif %}
        </div>

        <ol class="wrap_cont ulist">
          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">1</span>
                <strong class="tit_info">
                  카카오톡에 로그인 된 계정이 아닌, 다른 계정으로도 로그인 가능한가요?
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample1">
              <div class="content ms-3">
                <div>불가능합니다.</div>
                <div>기본적으로 카카오로그인을 통한 로그인만을 지원하고 있습니다.</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">2</span>
                <strong class="tit_info">
                  각종 문의는 어떻게 할 수 있나요?
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample2">
              <div class="content ms-3">
                <div>페이지 사용 중 불편을 겪으셨거나 기타 문의하실 내용이 있는 경우 아래 안내된 경로를 통해 문의하실 수 있습니다.</div>
                <div>로그인 > 우상단 메뉴 > 문의 > 문의하기</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample7" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">3</span>
                <strong class="tit_info">
                  문의 답변 확인
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample7">
              <div class="content ms-3">
                <div>문의하기로 문의한 글을 확인하는 방법은 문의한 글의 하단에 답변으로 알려드립니다.</div>
                <div>문의 > 내 문의보기 > 내가문의한 글 > 문의 답변</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample3" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">4</span>
                <strong class="tit_info">
                  채널톡 이용 안내
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample3">
              <div class="content ms-3">
                <div>간단한 궁금증은 쳇봇을 통해 해결 할 수 있습니다.</div>
                <div>운영자의 답변이 필요한 경우 다소 시간이 걸릴 수 있습니다.</div>
                <div>우측하단 > 말풍선 > 새문의하기</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample4" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">5</span>
                <strong class="tit_info">
                  여러 기기에 하나의 계정으로 이용한 경우 기록이 동기화되나요?
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample4">
              <div class="content ms-3">
                <div>동일한 계정이라면 어느기기에서든 열람 기록이 동기화됩니다.</div>
                <div>다만, 오프라인으로 열람한 기록이 소실된 경우 혹은 네트워크 환경이 불안정한 경우 등 열람기록이 유실된 경우 동기화 되지 않을 수 있습니다.</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample5" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">6</span>
                <strong class="tit_info">
                  채팅방에 글이 안써져요!
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample5">
              <div class="content ms-3">
                <div>방을 입장(생성)할 때 한글을 입력하면 안됩니다.</div>
                <div>방을 입장(생성)하실 때 꼭 영어 또는 숫자로 입력해주세요.</div>
                <div>상단 > 채팅 > 방입장(생성)</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample6" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">7</span>
                <strong class="tit_info">
                  쇼핑 결제 및 환불문의
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample6">
              <div class="content ms-3">
                <div>기본적으로 네이버를 통해 구입을 하신 상품이므로 네이버로 결제 및 환불을 받으시면 됩니다.</div>
                <div>네이버 > 로그인 > 네이버쇼핑 > MY쇼핑</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

          <li>
            <div class="info_tit">
              <a class="link_cont text-dark my-3" data-bs-toggle="collapse" href="#collapseExample8" role="button" aria-expanded="false" aria-controls="collapseExample">
                <span class="num_info">8</span>
                <strong class="tit_info">
                  프로필 사진 변경이 안되요!
                </strong>
              </a>
            </div>

            <div class="collapse ms-5" id="collapseExample8">
              <div class="content ms-3">
                <div>프로필 사진은 카카오톡 프로필 사진과 연동이 됩니다.</div>
                <div>카카오톡 프로필 사진을 변경 후 재로그인이 필요합니다.</div>
                <div>상단 > 로그아웃 > 로그인 > 카카오간편로그인</div>
              </div>
            </div>
          </li>
          <hr class="m-0">

        </ol>
      </article>
    </div>
    <div class="text-end mt-3">
      <a href="{% url 'vocies:create' %}" class="btn btn-outline-warning">문의하기</a>
    </div>
  </main>

  <style>
    body {
      background-image : url('{% static 'images/그룹카드배경3.jpg' %}');
      background-repeat : repeat;
      background-size : cover;
      {% comment %} color:white; {% endcomment %}
     }
     
    .wrap_keyword {
      border-top: 2px px solid #212121;
      margin-top: 26px;
      padding: 17px 5px 4px;
    }

    .screen_out {
      overflow: hidden;
      position: absolute;
      width: 0;
      height: 0;
      line-height: 0;
      text-indent: -9999px;
    }

    .wrap_cont {
      padding-bottom: 30px;
      border-top: 2px solid #000;
      border-bottom: 1px solid #000;
    }

    .cont_public .wrap_cont > .item_info {
      padding: 12px 0 16px;
      border-top: 1px solid #e8e8e8;
      overflow: hidden;
    }

    .cont_public .info_tit {
      overflow: hidden;
    }

    .num_info {
      float: left;
      width: 55px;
      margin: 0;
      font-size: 15px;
    }

    .tit_info {
      float: left;
      width: 540px;
      font-size: 15px;
      font-weight: normal;
      margin-right: 40px;
      margin-left: 5px;
    }

    .btn_arr {
      float: right;
      width: 16px;
      height: 16px;
      margin-right: 14px;
    }

    .cont_public .wrap_cont .link_cont {
      float: left;
      width: 740px;
      margin: 5px;
    }

    .cont_public .wrap_cont .num_info {
      float: left;
      width: 55px;
      margin: 0;
      font-size: 15px;
    }

    .cont_public .wrap_cont .tit_info {
      float: left;
      width: 540px;
      font-size: 15px;
      font-weight: normal;
      margin-right: 40px;
      margin-left: 5px;
    }

    .cont_public .wrap_cont .btn_arr {
      float: right;
      width: 16px;
      height: 16px;
      margin-right: 14px;
    }

    .cont_public .wrap_cont > .item_info .info_cont {
      display: none;
      overflow: hidden;
      width: 690px;
      text-align: left;
      margin: 15px 0 15px 60px;
      font-size: 15px;
      line-height: 27px;
    }

    .cont_public .wrap_cont > .item_info .info_cont {
      display: none;
      overflow: hidden;
      width: 690px;
      text-align: left;
      margin: 15px 0 15px 60px;
      font-size: 15px;
      line-height: 27px;
    }

    .cont_public .wrap_cont > .item_info:first-child {
      margin-top: 30px;
      border-top: 0 none;
    }

    .cont_public .wrap_cont > .item_info {
      padding: 12px 0 16px;
      border-top: 1px solid #e8e8e8;
      overflow: hidden;
    }

    .ulist {
      list-style: none;
    }
  </style>
{% endblock content %}

vocies/templates/vocies/manage_page.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}

  <div class="content">

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-10">

          <div class="row justify-content-center">
            <div class="col-md-6">
              <p><img src="{%static "images/as.svg"%}" alt="Image" class="img-fluid"></p>
            </div>
            <div class="col-md-6">
              <h1 class="text-center">모든 문의</h1>
              {% for vocie in vocies %}
                <div class="d-flex justify-content-center my-3">
                  <a href="{% url 'vocies:detail' vocie.pk %}" class="text-decoration-none text-dark">{{ vocie.title }}
                    {% if not vocie.vocie_comment.count %}
                      <span class="text-danger fw-bold">(아직 답변이 없습니다)</span>
                    {% else %}
                      <span class="text-success fw-bold">(답변이 완료되었습니다)</span>
                    {% endif %}

                    <span>{{ vocie.user.nickname }}</span>
                  </div>
                </a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style>
    body {
      font-family: "Roboto", sans-serif;
      background-color: #fff;
      line-height: 1.9;
      color: #8c8c8c;
    }

    .h1,
    .h2,
    .h3,
    .h4,
    .h5,
    .h6,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Roboto", sans-serif;
      color: #000;
    }

    a {
      -webkit-transition: 0.3s all ease;
      -o-transition: 0.3s all ease;
      transition: 0.3s all ease;
    }

    a,
    a:hover {
      text-decoration: none !important;
    }

    .text-black {
      color: #000;
    }

    .content {
      padding: 7rem 0;
    }

    .heading {
      font-size: 2.5rem;
      font-weight: 900;
    }

    .form-control {
      border: none;
      background: #f3f3f3;
    }

    .form-control:active,
    .form-control:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
      background: #f3f3f3;
    }

    .col-form-label {
      color: #000;
    }

    .btn,
    .custom-select,
    .form-control {
      height: 50px;
    }

    .custom-select:active,
    .custom-select:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
      border-color: #000;
    }

    .btn {
      border: none;
      border-radius: 4px !important;
    }

    .btn.btn-primary {
      background: #000;
      color: #fff;
      padding: 15px 20px;
    }

    .btn:hover {
      color: #fff;
    }

    .btn:active,
    .btn:focus {
      outline: none;
      -webkit-box-shadow: none;
      box-shadow: none;
    }

    .box {
      padding: 40px;
      background: #fff;
      -webkit-box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
      box-shadow: -30px 30px 0 0 rgba(0, 0, 0, 0.08);
    }

    .box h3 {
      font-size: 14px;
      margin-bottom: 30px;
      text-align: center;
    }

    label.error {
      font-size: 12px;
      color: red;
    }

    #message {
      resize: vertical;
    }

    #form-message-success,
    #form-message-warning {
      display: none;
    }

    #form-message-warning {
      color: #B90B0B;
    }

    #form-message-success {
      color: #55A44E;
      font-size: 18px;
      font-weight: bold;
    }

    .submitting {
      float: left;
      width: 100%;
      padding: 10px 0;
      display: none;
      font-weight: bold;
      font-size: 12px;
      color: #000;
    }
  </style>
{% endblock content %}