accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("kakao/login/callback/", views.kakao_callback, name="kakao_callback"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("mypage/", views.mypage, name="mypage"),
    path("update/", views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("<int:pk>/block/", views.block, name="block"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    # path("profile/<str:username>/", views.profile, name="profile"),
    path("save/", views.save, name="save"),
    path("notice/", views.notice, name="notice"),
    path("test/", views.test, name="test"),
]

cards/urls.py
from django.urls import path
from . import views

app_name = "cards"

urlpatterns = [
    path("", views.index, name="index"),
    # 개인카드
    path("create/indiv/", views.usercard_create, name="usercard_create"),
    path("create/indiv/2", views.usercard_create2, name="usercard_create2"),
    path("detail/usercard/<int:pk>/", views.usercard_detail, name="usercard_detail"),
    path("<int:pk>/usercard/update/", views.usercard_update, name="usercard_update"),
    path("<int:pk>/usercard/update/2", views.usercard_update2, name="usercard_update2"),
    path("usercard/delete/", views.usercard_delete, name="usercard_delete"),
    path("<int:pk>/usercard/comments/", views.usercard_comment, name="usercard_comment"),
    path(
        "<int:pk>/usercard/comments/2",
        views.usercard_comment2,
        name="usercard_comment2",
    ),
    path("<int:pk>/modal_open/", views.modal_open, name="modal_open"),
    # 그룹카드
    path("create/group/", views.group_create, name="group_create"),
    path("<int:pk>/create/group/2", views.group_create2, name="group_create2"),
    path("detail/group/<int:pk>/", views.group_detail, name="group_detail"),
    path("<int:pk>/group/update/", views.groupcard_update, name="groupcard_update"),
    path("<int:pk>/group/update/2", views.groupcard_update2, name="groupcard_update2"),
    path("<int:pk>/group/delete/", views.groupcard_delete, name="groupcard_delete"),
    path("<int:pk>/gcomments/", views.gcomment_create, name="gcomment_create"),
    path("<int:pk>/gcomments/2", views.gcomment_create2, name="gcomment_create2"),
    path("search/", views.search, name="search"),
    # path(
    #     "<int:cards_pk>/group/<int:comment_pk>/delete/",
    #     views.gcomments_delete,
    #     name="gcomments_delete",
    # ),
]

chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
]

notes/urls.py
from . import views
from django.urls import path

app_name = "notes"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/send/", views.send, name="send"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

semi_pjt_2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from meetings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("cards/", include("cards.urls")),
    path("vocies/", include("vocies.urls")),
    path("accounts/", include("accounts.urls")),
    path("meetings/", include("meetings.urls")),
    path("chat/", include("chat.urls")),
    path("shoppings/", include("shoppings.urls")),
    path("notes/", include("notes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vocies/urls.py
from django.urls import path
from . import views

app_name = "vocies"

urlpatterns = [
    path("", views.index, name="index"),
    path("myvocie/", views.myvocie, name="myvocie"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/comment/", views.comment, name="comment"),
    path("manage_page/", views.manage_page, name="manage_page"),
    path("<int:pk>/<int:super_pk>/delete_comment/", views.delete_comment, name="delete_comment"),
]

templates/base111 2.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} 폰트 {% endcomment %}
    <link href="https://fonts.googleapis.com/css2?family=Jua&family=Noto+Sans+KR:wght@500&display=swap"
    rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'style.css' %}?{% now 'U'%}" />
    {% comment %} 폰트 {% endcomment %}
    <title>이름 정하기</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <script src="{% static 'js/chat.js' %}"></script>
    {% bootstrap_css %}

<body>
  <div class="modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header d-flex flex-column">
          <h1 class='text-center my-5'>카카오 로그인</h1>
          <div class="d-grid">
            <a href="{% url 'accounts:kakao' %}">
              <img src="{% static 'images/kakao_login.jpg' %}" alt="카카오 간편로그인" style='width:30rem' class='rounded-3'>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">대표이사 문경욱</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:index' %}">회원</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'cards:index' %}">벽난로</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'meetings:index' %}">모임</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'chat:index' %}">채팅</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:profile' request.user.pk %}">프로필</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'vocies:index' %}">문의</a>
          </li>
          <li class="nav-item dropdown d-flex align-items-center">
            {% if request.user.tree_notice or request.user.note_notice %}
              {% if request.user.notice_tree and request.user.notice_note %}
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-bell fw-bold text-danger "></i>
              </a>
              <ul class="dropdown-menu p-0">
                <li class="p-3">새로운 알림이 <br> 없어요😊</li>
              </ul>
              {% else %}
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" onclick="apen(event)">
                <i class="bi bi-bell-fill fw-bold text-danger"></i>
              </a>
              {% csrf_token %}
              <ul class="dropdown-menu p-0" id="dropul">
              </ul>
              {% endif %}
            {% else %}
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-bell-slash-fill fw-bold text-danger"></i>
            </a>
            <ul class="dropdown-menu p-0">
              <li class="p-3">알림을 켜두면 <br>새로운 알림을 <br> 받을 수 있어요😊</li>
            </ul>
            {% endif %}
          </li>
          {% else %}
          <li class="navbar-brand">
            <button type="button" class="nav-link border-0 bg-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
              로그인
            </button>
          </li>
          {% endif %} 
              <audio controls>
                <source src="{%static 'sounds/jinglebell.mp3' %}" type="audio/mp3">
              </audio>
          <li class="navbar-brand">
              {% for message in messages %}
              <div class="nav-link alert {{ message.tags }} alert-auto-dismissible text-center d-flex align-items-center m-0" role="alert" style="height: 40px; font-size: 16px;">
            {{ message }}
              </div>
              {% endfor %}
          </li>
        </ul>
      </div> 
    </div>
  </nav>
    {% block content %}
    {% endblock  %}
    {% bootstrap_javascript %}
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 2000);
        function apen(event) {
          const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
          axios({
            method: 'post',
            url: '/accounts/notice/',
            headers: {'X-CSRFToken': csrftoken},
          })
          .then(response => {
            const items = response.data.items
            const dropul= document.querySelector("#dropul")
            removeAllchild(dropul)
            function removeAllchild(div) {
              while (div.hasChildNodes()) {
                div.removeChild(div.firstChild);
              }
            };
            for (let i=0; i<items.length; i++) {
              let time = moment(items[i][0]).add(9, 'hours').format('YYYY년 MM월 D일, a h:mm:ss');
              console.log(time)
              if (items[i][1][2] === 'card') {
                const li = document.createElement('li')
                const a = document.createElement('a')
                a.className='dropdown-item'
                a.href = `{% url 'cards:usercard_detail' 1 %}`
                a.href = a.href.replace('1', items[i][1][3])
                const p = document.createElement('p')
                const h6 = document.createElement('h6')
                h6.innerText = time
                p.innerText = `${items[i][1][1]} 님이 트리에 ${items[i][1][0]} 을 남겼어요.`
                a.appendChild(h6)
                a.appendChild(p)
                li.appendChild(a)
                dropul.appendChild(li)
              }
              else {
                const li = document.createElement('li')
                const a = document.createElement('a')
                a.className='dropdown-item'
                a.href = `{% url 'notes:detail' 1 %}`
                a.href = a.href.replace('1', items[i][1][3])
                const p = document.createElement('p')
                const h6 = document.createElement('h6')
                h6.innerText = time
                p.innerText = `${items[i][1][1]} 님이 ${items[i][1][0]} 쪽지를 보냈어요.`
                a.appendChild(h6)
                a.appendChild(p)
                li.appendChild(a)
                dropul.appendChild(li)
              }
            }
          })
        }
    </script>
  </body>
</html>

templates/base111.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} 폰트 {% endcomment %}
    <link href="https://fonts.googleapis.com/css2?family=Jua&family=Noto+Sans+KR:wght@500&display=swap"
    rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'style.css' %}?{% now 'U'%}" />
    {% comment %} 폰트 {% endcomment %}
    <title>이름 정하기</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet">
    <script src="{% static 'js/chat.js' %}"></script>
    {% bootstrap_css %}

<body>
  <div class="modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header d-flex flex-column">
          <h1 class='text-center my-5'>카카오 로그인</h1>
          <div class="d-grid">
            <a href="{% url 'accounts:kakao' %}">
              <img src="{% static 'images/kakao_login.jpg' %}" alt="카카오 간편로그인" style='width:30rem' class='rounded-3'>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">대표이사 문경욱</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:index' %}">회원</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'cards:index' %}">벽난로</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'meetings:index' %}">모임</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'chat:index' %}">채팅</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'accounts:profile' request.user.pk %}">프로필</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link" href="{% url 'vocies:index' %}">문의</a>
          </li>
          <li class="nav-item dropdown d-flex align-items-center">
            {% if request.user.tree_notice or request.user.note_notice %}
              {% if request.user.notice_tree and request.user.notice_note %}
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-bell fw-bold text-danger "></i>
              </a>
              <ul class="dropdown-menu p-0">
                <li class="p-3">새로운 알림이 <br> 없어요😊</li>
              </ul>
              {% else %}
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" onclick="apen(event)">
                <i class="bi bi-bell-fill fw-bold text-danger"></i>
              </a>
              {% csrf_token %}
              <ul class="dropdown-menu p-0" id="dropul">
              </ul>
              {% endif %}
            {% else %}
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-bell-slash-fill fw-bold text-danger"></i>
            </a>
            <ul class="dropdown-menu p-0">
              <li class="p-3">알림을 켜두면 <br>새로운 알림을 <br> 받을 수 있어요😊</li>
            </ul>
            {% endif %}
          </li>
          {% else %}
          <li class="navbar-brand">
            <button type="button" class="nav-link border-0 bg-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
              로그인
            </button>
          </li>
          {% endif %} 
              <audio controls>
                <source src="{%static 'sounds/jinglebell.mp3' %}" type="audio/mp3">
              </audio>
          <li class="navbar-brand">
              {% for message in messages %}
              <div class="nav-link alert {{ message.tags }} alert-auto-dismissible text-center d-flex align-items-center m-0" role="alert" style="height: 40px; font-size: 16px;">
            {{ message }}
              </div>
              {% endfor %}
          </li>
        </ul>
      </div> 
    </div>
  </nav>
    {% block content %}
    {% endblock  %}
    {% bootstrap_javascript %}
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script>
        window.setTimeout(function() {
            $(".alert-auto-dismissible").fadeTo(500, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 2000);
        function apen(event) {
          const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
          axios({
            method: 'post',
            url: '/accounts/notice/',
            headers: {'X-CSRFToken': csrftoken},
          })
          .then(response => {
            const items = response.data.items
            const dropul= document.querySelector("#dropul")
            removeAllchild(dropul)
            function removeAllchild(div) {
              while (div.hasChildNodes()) {
                div.removeChild(div.firstChild);
              }
            };
            for (let i=0; i<items.length; i++) {
              let time = moment(items[i][0]).add(9, 'hours').format('YYYY년 MM월 D일, a h:mm:ss');
              console.log(time)
              if (items[i][1][2] === 'card') {
                const li = document.createElement('li')
                const a = document.createElement('a')
                a.className='dropdown-item'
                a.href = `{% url 'cards:usercard_detail' 1 %}`
                a.href = a.href.replace('1', items[i][1][3])
                const p = document.createElement('p')
                const h6 = document.createElement('h6')
                h6.innerText = time
                p.innerText = `${items[i][1][1]} 님이 트리에 ${items[i][1][0]} 을 남겼어요.`
                a.appendChild(h6)
                a.appendChild(p)
                li.appendChild(a)
                dropul.appendChild(li)
              }
              else {
                const li = document.createElement('li')
                const a = document.createElement('a')
                a.className='dropdown-item'
                a.href = `{% url 'notes:detail' 1 %}`
                a.href = a.href.replace('1', items[i][1][3])
                const p = document.createElement('p')
                const h6 = document.createElement('h6')
                h6.innerText = time
                p.innerText = `${items[i][1][1]} 님이 ${items[i][1][0]} 쪽지를 보냈어요.`
                a.appendChild(h6)
                a.appendChild(p)
                li.appendChild(a)
                dropul.appendChild(li)
              }
            }
          })
        }
    </script>
  </body>
</html>